name: login
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  lottie: ^2.6.0
  day_night_switcher: ^0.2.0+1
  concentric_transition: ^1.0.3
  flutter:
    sdk: flutter

cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/.
  - lib/assets/.